not True = False
not False = True
True or True = True
True or False = True
False or False = False #or either
False or True = True
True and True = True
True and False = False
False and False = False #and both
False and True = False